# Generated by Django 4.0.6 on 2023-11-03 23:22

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_metric', models.BooleanField(default=True)),
                ('fats', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='users/default_avatar.png', force_format=None, keep_meta=False, quality=75, scale=None, size=[160, 160], upload_to=core.utils.UploadAndRename('users/profile_pictures'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
