# Generated by Django 4.0.6 on 2022-07-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diet",
            name="slug",
            field=models.SlugField(
                error_messages={"unique": "This name has already been used."},
                unique=True,
            ),
        ),
    ]
