# Generated by Django 4.0.4 on 2022-05-16 16:53

import diets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntermediaryMealIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(
                default="ingr_thumb/default.jpg", upload_to="ingr_thumb"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(default="ingr", max_length=50),
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="mymeal", max_length=50)),
                ("description", models.CharField(max_length=50, null=True)),
                ("recipe", models.TextField(max_length=1000, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="meal_thumb/default.jpg", upload_to="meal_thumb"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=models.SET(diets.models.get_sentinel),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        through="diets.IntermediaryMealIngredient",
                        to="diets.ingredient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="intermediarymealingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diets.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="intermediarymealingredient",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diets.meal"
            ),
        ),
    ]
