# Generated by Django 4.0.6 on 2022-07-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0002_alter_diet_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diet",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
