# Generated by Django 4.0.4 on 2022-05-20 01:04

import diets.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diets", "0003_day_intermediarydaymeal_day_meals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intermediarydaymeal",
            name="meal_num",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="intermediarymealingredient",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("public", models.BooleanField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=models.SET(diets.models.get_sentinel),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("days", models.ManyToManyField(to="diets.meal")),
            ],
        ),
    ]
