# Generated by Django 4.0.4 on 2022-05-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_alter_intermediarydaymeal_meal_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='days',
            field=models.ManyToManyField(to='diets.day'),
        ),
    ]
