# Generated by Django 4.0.4 on 2022-05-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_alter_diet_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='backup',
            field=models.BooleanField(default=False),
        ),
    ]
