# Generated by Django 4.0.6 on 2022-07-24 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0006_alter_day_author_alter_diet_author_alter_meal_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="end_date",
            field=models.DateField(default=datetime.date(2022, 10, 2)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diet",
            name="date",
            field=models.DateField(),
        ),
    ]
