# Generated by Django 4.0.4 on 2022-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0006_day_backup"),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="url_slug",
            field=models.SlugField(default="slug"),
        ),
    ]
