# Generated by Django 4.0.4 on 2022-05-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0007_diet_url_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diet",
            name="url_slug",
        ),
    ]
