# Generated by Django 4.0.4 on 2022-05-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0010_rename_desc_diet_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="url",
            field=models.URLField(null=True),
            preserve_default=False,
        ),
    ]
