# Generated by Django 4.0.4 on 2022-05-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0012_alter_diet_public"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IntermediaryDayMeal",
            new_name="ThroughDM",
        ),
        migrations.RenameModel(
            old_name="IntermediaryMealIngredient",
            new_name="ThroughMI",
        ),
    ]
