# Generated by Django 4.0.4 on 2022-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0014_rename_throughdm_throughdaymeal_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diet",
            options={"ordering": ["-pk"]},
        ),
    ]
