# Generated by Django 4.0.4 on 2022-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0015_alter_diet_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["-pk"]},
        ),
    ]
