# Generated by Django 4.0.4 on 2022-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0016_alter_meal_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diet",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["pk"]},
        ),
    ]
