name: Build and run
on: [push]
jobs:
  django_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Copy the sample env file
      run: mv .env.sample .env.dev
    - name: Build the docker compose environment
      run: docker-compose up -d
    - name: Run migrations
      run: docker-compose run web python manage.py migrate
    - name: Run tests
      run: docker-compose run web python manage.py test
