name: Django app
on: [push]
jobs:
  django_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the docker image
      run: docker-compose up -d
    - name: Make migrations
      run: docker-compose run web python manage.py makemigrations
    - name: Run migrations
      run: docker-compose run web python manage.py migrate
    - name: Run tests
      run: docker-compose run web python manage.py test
