name: Build Docker Image

on:
  push

jobs:
  django:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: typicalam
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: src
          push: true
          tags: "typicalam/sparesnack:latest,typicalam/sparesnack:${{ env.GITHUB_SHA_SHORT }}"
          file: ./src/Dockerfile.prod

  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: typicalam
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: nginx
          push: true
          tags: "typicalam/sparesnack-nginx:latest,typicalam/sparesnack-nginx:${{ env.GITHUB_SHA_SHORT }}"
          file: ./nginx/Dockerfile
